CREATE TABLE STUDENT (
    id BIGINT PRIMARY KEY,
    USN VARCHAR(20) NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PHONE VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(250)
);
CREATE TABLE PROJECT (
    pid BIGINT PRIMARY KEY,
    sid BIGINT,
    FOREIGN KEY (sid) REFERENCES STUDENT(sid),
    image_path VARCHAR(255),
    title VARCHAR(50) NOT NULL,
    date VARCHAR(20) NOT NULL,
    location VARCHAR(100) NOT NULL,
    description varchar(10000) NOT NULL
);
